name: Generate Snake
on:
  schedule: 
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: Gauravvgithub
          outputs: dist/github-contribution-grid-snake.svg
      - name: Push changes
        uses: EndBug/add-and-commit@v7
        with:
          message: "Generated snake animation"
          add: "dist/github-contribution-grid-snake.svg"
